### ISSUE TITLE
Incorrect port number

### ISSUE THREAD

**Issue by malikluti** [ontop/ontop-patterns-tutorial#2]
Hello,

I found a bug in the tutorial. Step number five is asking to reach the SPARQL endpoint through the following URL (http://localhost:8880/sparql), however, the port number is incorrect. It should be port 8080 according to step four of the tutorial. Hence the correct instruction should be

A SPARQL endpoint backed by ontop at URL http://localhost:8080/sparql (assuming default port **8080** is used), which may be accessed using any HTTP client, including SPARQL clients and tools using the standard SPARQL HTTP protocol. For instance, using curl:
curl --request POST
--url http://localhost:8080/sparql
--header 'accept: application/json'
--header 'content-type: application/sparql-query'
--data 'SELECT * { ?s ?p ?o } LIMIT 5'

**Instead of:**

A SPARQL endpoint backed by ontop at URL http://localhost:8880/sparql (assuming default port 8880 is used), which may be accessed using any HTTP client, including SPARQL clients and tools using the standard SPARQL HTTP protocol. For instance, using curl:
curl --request POST
--url http://localhost:8880/sparql
--header 'accept: application/json'
--header 'content-type: application/sparql-query'
--data 'SELECT * { ?s ?p ?o } LIMIT 5'

The same mistake also exists in the deployment instructions of SPARQL endpoint using Docker.

**Comment by ghxiao** [comment]
Thank you. It has been fixed.
